In [5]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(arr)
arr.ndim
arr.size
arr.shape


[[1 2 3]
 [3 4 5]
 [6 7 8]]


(3, 3)

In [ ]:
new_arr=np.array([[[5,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print(new_arr)
new_arr.shape

[[[5 1 1]
  [2 2 2]
  [3 3 3]]]


(1, 3, 3)

In [12]:
arr1=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]],[[5,5,5],[6,6,6]]])
print(arr1)
arr1.shape

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]


(3, 2, 3)

In [ ]:
arr1=np.array([[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[3,3,3],[4,4,4]],[[6,6,6],[5,5,5],[6,6,6]]])
print(arr1)
arr1.shape

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[1 1 1]
  [3 3 3]
  [4 4 4]]

 [[6 6 6]
  [5 5 5]
  [6 6 6]]]


(3, 3, 3)

In [15]:
arr1=np.array([[[1,1],[2,2]],[[3,3],[4,4]],[[5,5],[6,6]]])
print(arr1)
arr1.shape

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]

 [[5 5]
  [6 6]]]


(3, 2, 2)

In [ ]:
arr2= np.array([1,2])
print(arr2)
arr2.shape

[1 2]


(2,)

In [20]:
arr3= np.array([[1,2],[3,4]])
print(arr3)
arr3.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#In 3d array we calculate row, column, depth(calculate channel) in shape property
#depth=total channel/total no number of row
arr4= np.array([[[1,1],[2,2],[3,3]]])
print(arr4)
arr4.shape

[[[1 1]
  [2 2]
  [3 3]]]


(1, 3, 2)

In [26]:
arr5= np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]],[[5,5,5],[6,6,6]]])
print(arr5)
print(arr5.size)
arr5.shape

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
18


(3, 2, 3)